### ISSUE TITLE
unit tests not working because of plotly 

### ISSUE THREAD

**Issue by laureleya** [lumen-org/LumenReact#51]
log for test:

npm test
  shell: /bin/bash -e {0}

> lumen-react@0.1.0 test /home/runner/work/LumenReact/LumenReact
> react-scripts test

FAIL src/App.test.js
  ● Test suite failed to run

    TypeError: window.URL.createObjectURL is not a function

       5 | import "./StandardPlot.css";
       6 | import { defaultPlot } from "./defaultPlot";
    >  7 | import Plot from "react-plotly.js";
         | ^
       8 | 
       9 | class StandardPlot extends Component {
      10 |   static propTypes = {

      at define (node_modules/plotly.js/dist/plotly.js:58970:37)
      at node_modules/plotly.js/dist/plotly.js:58979:1
      at r (node_modules/plotly.js/dist/plotly.js:58949:81)
      at Object.430 (node_modules/plotly.js/dist/plotly.js:58952:2)
      at o (node_modules/plotly.js/dist/plotly.js:7:631)
      at node_modules/plotly.js/dist/plotly.js:7:682
      at Object.840.../../components/drawing (node_modules/plotly.js/dist/plotly.js:139674:16)
      at o (node_modules/plotly.js/dist/plotly.js:7:631)
      at node_modules/plotly.js/dist/plotly.js:7:682
      at Object.1210.../../plots/mapbox (node_modules/plotly.js/dist/plotly.js:194490:21)
      at o (node_modules/plotly.js/dist/plotly.js:7:631)
      at node_modules/plotly.js/dist/plotly.js:7:682
      at Object.40.../src/traces/scattermapbox (node_modules/plotly.js/dist/plotly.js:666:18)
      at o (node_modules/plotly.js/dist/plotly.js:7:631)
      at node_modules/plotly.js/dist/plotly.js:7:682
      at Object.26../aggregate (node_modules/plotly.js/dist/plotly.js:441:5)
      at o (node_modules/plotly.js/dist/plotly.js:7:631)
      at r (node_modules/plotly.js/dist/plotly.js:7:797)
      at node_modules/plotly.js/dist/plotly.js:7:826
      at node_modules/plotly.js/dist/plotly.js:7:88
      at Object.<anonymous> (node_modules/plotly.js/dist/plotly.js:7:322)
      at Object.<anonymous> (node_modules/src/react-plotly.js:2:1)
      at Object.<anonymous> (src/components/StandardPlot/StandardPlot.js:7:1)
      at Object.<anonymous> (src/components/StandardPlot/StandardPlotContainer.js:11:1)
      at Object.<anonymous> (src/sections/VisualizationCanvas/VisualizationCanvas.js:8:1)
      at Object.<anonymous> (src/sections/VisualizationCanvas/VisualizationCanvasContainer.js:3:1)
      at Object.<anonymous> (src/sections/VisualizationCanvas/index.js:1:1)
      at Object.<anonymous> (src/sections/MainWindows/MainWindows.js:4:1)
      at Object.<anonymous> (src/sections/MainWindows/MainWindowsContainer.js:3:1)
      at Object.<anonymous> (src/sections/MainWindows/index.js:1:1)
      at Object.<anonymous> (src/App.js:4:1)
      at Object.<anonymous> (src/App.test.js:3:1)

**Comment by laureleya** [comment]
In my VS, hovering over the import Plot from "react-plotly.js" shows: 

> Could not find a declaration file for module 'react-plotly.js'. '/home/my_dir/LumenReact/node_modules/react-plotly.js/react-plotly.js' implicitly has an 'any' type.
  Try `npm install @types/react-plotly.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-plotly.js';`ts(7016)

I already tried inserting a .d.ts file as well as uninstall and installing react-plotly.js

**Comment by laureleya** [comment]
https://stackoverflow.com/questions/52968969/jest-url-createobjecturl-is-not-a-function
Here, people have a similar problem

**Comment by laureleya** [comment]
I used the last workaround with inserting
`window.URL.createObjectURL = function() {};`
in the setupTest.js.
